version: "3"

services:
  tezedge-memprof:
    image: tezedge/tezedge-memprof:latest
    privileged: true
    environment:
      - TEZEDGE_NODE_NAME=deploy-monitoring-tezedge-node
    volumes:
      - "/sys/kernel/debug:/sys/kernel/debug:rw"
      - "/proc:/proc:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    ports:
      - "17832:17832"

  tezedge-debugger:
    image: tezedge/tezedge-debugger:latest
    privileged: true
    environment:
      - RUST_BACKTRACE=1
    volumes:
      - "tezedge-shared-data:/tmp/volume/tezedge:ro"
      - "ocaml-shared-data:/tmp/volume/tezos:ro"
      - "./debugger-config.toml:/home/appuser/config.toml:ro"
      - "/sys/kernel/debug:/sys/kernel/debug:rw"
      - "/tmp/report:/tmp/report:rw"
      - "debugger-data:/tmp/debugger_database"
    ports:
      - "17732:17732"      # debugger RPC port
      - "10001:10001/udp"  # debugger syslog port for tezedge node
      - "11001:11001/udp"  # debugger syslog port for tezos node

  tezedge-node:
    image: tezedge/tezedge:latest-frame-pointers-enabled
    environment:
      - TEZOS_CONTEXT=index-log-size=2_500_000
    command: ["--network", "${TEZOS_NETWORK}", "--p2p-port=9732", "--rpc-port=18732", "--websocket-address=0.0.0.0:4927", "--log", "terminal", "file", "--log-file", "/tmp/tezedge/tezedge.log", "--tezos-context-storage", "both", "--context-stats-db-path", "context-stats-db", "--peer-thresh-low", "60", "--peer-thresh-high", "80"]
    logging:
      # Produce syslogs instead of terminal logs
      driver: "syslog"
      options:
        # Send the logs to syslog (UDP only) server (running on debugger)
        syslog-address: "udp://0.0.0.0:10001"  # Port must match debugger syslog port in 'ports' section
        # Always in same RFC 5424 format (with microseconds precision)
        syslog-format: "rfc5424micro"
    volumes:
      - "tezedge-shared-data:/tmp/tezedge"
    ports:
      - "4927:4927"       # node WS port (required only for tezedge)
      - "9732:9732"       # node P2P port
      - "18732:18732"     # node RPC port
      - "3030:3030"       # sandbox launcher port

  tezedge-sandbox:
    image: tezedge/tezedge:sandbox-latest
    logging:
      # Produce syslogs instead of terminal logs
      driver: "syslog"
      options:
        # Send the logs to syslog (UDP only) server (running on debugger)
        syslog-address: "udp://0.0.0.0:10001"  # Port must match debugger syslog port in 'ports' section
        # Always in same RFC 5424 format (with microseconds precision)
        syslog-format: "rfc5424micro"
    volumes:
      - "tezedge-shared-data:/tmp/tezedge"
    ports:
      - "4927:4927"       # node WS port (required only for tezedge)
      - "9732:9732"       # node P2P port
      - "18732:18732"     # node RPC port
      - "3030:3030"       # sandbox launcher port

  ocaml-node:
    image: tezos/tezos:v9-release
    entrypoint: sh -c "sleep 5 && /usr/local/bin/entrypoint.sh tezos-node --cors-header='content-type' --cors-origin='*' --rpc-addr=[::]:18733 --net-addr=[::]:9733 --history-mode archive --network ${TEZOS_NETWORK}"
    logging:
      # Produce syslogs instead of terminal logs
      driver: "syslog"
      options:
        # Send the logs to syslog (UDP only) server (running on debugger)
        syslog-address: "udp://0.0.0.0:11001"  # Port must match debugger syslog port in 'ports' section
        # Always in same RFC 5424 format (with microseconds precision)
        syslog-format: "rfc5424micro"
    volumes:
      - "ocaml-shared-data:/var/run/tezos/node"
    ports:
      # should be equal inside docker and outside, because the node tells this port in its connection message,
      # that is how peers can connect to it later
      - "9733:9733"
      - "18733:18733"     # node RPC port

  explorer:
    image: tezedge/tezedge-explorer:latest
    environment:
      # need a better way to provide such information
      - API=[{"id":"rust","type":"tezedge","name":"rust.${HOSTNAME}.dev.tezedge.com","http":"http://${HOSTNAME}.dev.tezedge.com:18732","p2p_port":9732,"features":[{"name":"ws","url":"ws://${HOSTNAME}.dev.tezedge.com:4927"},{"name":"debugger","url":"http://${HOSTNAME}.dev.tezedge.com:17732"},{"name":"monitoring"},{"name":"resources/system","monitoringUrl":"http://${HOSTNAME}.dev.tezedge.com:38732/resources/tezedge"},{"name":"resources/memory","memoryProfilerUrl":"http://${HOSTNAME}.dev.tezedge.com:17832"},{"name":"resources/storage"},{"name":"mempool"},{"name":"storage"},{"name":"network"},{"name":"logs"}]},{"id":"ocaml","type":"octez","name":"ocaml.${HOSTNAME}.dev.tezedge.com","http":"http://${HOSTNAME}.dev.tezedge.com:18733","p2p_port":9733,"features":[{"name":"debugger","url":"http://${HOSTNAME}.dev.tezedge.com:17732"},{"name":"monitoring"},{"name":"resources/system","monitoringUrl":"http://${HOSTNAME}.dev.tezedge.com:38732/resources/ocaml"},{"name":"resources/memory","memoryProfilerUrl":"http://${HOSTNAME}.dev.tezedge.com:17832"},{"name":"resources/storage"},{"name":"mempool"},{"name":"network"},{"name":"logs"}]}]
    ports:
      - "80:80"
volumes:
  tezedge-shared-data:
    external: false
  ocaml-shared-data:
    external: false
  debugger-data:
    external: false
