# Build stage 1
FROM debian:buster
# Install required packages
RUN apt-get update && \
    apt-get -y install gnupg wget && \
    wget https://apt.llvm.org/llvm-snapshot.gpg.key && apt-key add llvm-snapshot.gpg.key && rm llvm-snapshot.gpg.key && \
    apt-get -y install software-properties-common && \
    add-apt-repository 'deb http://apt.llvm.org/buster/ llvm-toolchain-buster-8 main' && \
    apt-get update && \
    apt-get install -y rsync git m4 build-essential patch unzip bubblewrap pkg-config \
                       libgmp-dev libev-dev libhidapi-dev libffi6 libffi-dev liblmdb-dev curl jq opam \
                       libsodium23 libsodium-dev \
                       libllvm-8-ocaml-dev libllvm8 llvm-8 llvm-8-dev \
                       clang-8 libclang-8-dev
# Install ocaml compiler and dune
ARG OCAML_VERSION="4.07.1"
ENV OPAMNO 1
RUN opam init --bare --disable-sandboxing && \
    opam switch create ${OCAML_VERSION} && \
    opam switch set ${OCAML_VERSION} && \
    opam update
ENV OPAMNO  0
ENV OPAMYES 1
RUN opam install dune
# Set opam env variables
ENV OPAM_SWITCH_PREFIX="/root/.opam/${OCAML_VERSION}"
ENV CAML_LD_LIBRARY_PATH="/root/.opam/${OCAML_VERSION}/lib/stublibs:/root/.opam/${OCAML_VERSION}/lib/ocaml/stublibs:/root/.opam/${OCAML_VERSION}/lib/ocaml"
ENV OCAML_TOPLEVEL_PATH="/root/.opam/${OCAML_VERSION}/lib/toplevel"
ENV MANPATH=":/root/.opam/${OCAML_VERSION}/man"
ENV PATH="/root/.opam/${OCAML_VERSION}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
# Checkout and compile tezos-rs source code
RUN curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
ENV PATH=/root/.cargo/bin:$PATH
ENV RUST_BACKTRACE=1
ENV SODIUM_USE_PKG_CONFIG=1
ENV OCAML_BUILD_CHAIN=local
RUN git clone https://github.com/simplestaking/tezos-rs.git && \
    cd tezos-rs && \
    cargo build

# Build stage 2
FROM debian:buster
COPY --from=0 /tezos-rs/target/debug/light-node /bin/light-node
COPY --from=0 /tezos-rs/tezos_interop/lib_tezos/artifacts/libtezos.o /lib/libtezos.o
COPY --from=0 /tezos-rs/light_node/config /config
RUN apt-get update && \
    apt-get install -y libgmp-dev libev-dev libsodium23
ENTRYPOINT ["light-node", "--tezos-data-dir", "/tmp"]