[package]
name = "tezos_lib_storage_ffi"
version = "1.9.0"
authors = ["Bruno Deferrari <bruno.deferrari@viablesystems.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocaml-interop = { version = "0.8.7", features = ["without-ocamlopt", "caml-state"] }
# local dependencies
tezos_interop = { path = "../interop" }
tezos_context = { path = "../context" }

[dev-dependencies]
tempfile = "3"