[package]
name = "tezos_lib_storage_ffi"
version = "1.7.0"
authors = ["Bruno Deferrari <bruno.deferrari@viablesystems.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocaml-interop = { version = "0.8.4", features = ["without-ocamlopt", "caml-state"] }

[dev-dependencies]
tempfile = "3"
tezos_new_context = { path = "../new_context" }
