- hosts: "*"
  become: yes
  vars_files:
    - ../vars/variables.yml

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Add user to docker group
      user:
        name: "{{ target_hosts_user }}"
        shell: /bin/bash
        groups: docker
        append: yes

    - name: Deploy {{ ssh_config_file }}
      template:
        src   : ../templates/ssh_config.j2
        dest  : "{{ ssh_config_file }}"
        owner : root
        group : root
        mode  : 0600